import React from 'react';
import { TrichologyProvider, useTrichology } from './context/TrichologyContext';
import { Header } from './components/layout/Header';
import { IntakeForm } from './components/intake/IntakeForm';
import { AssessmentReport } from './components/report/AssessmentReport';
import { HistoryTracker } from './components/tracker/HistoryTracker';
import { Dna, ShieldCheck, Heart } from 'lucide-react';

const MainContent: React.FC = () => {
  const { activeTab } = useTrichology();

  return (
    <main className="px-4 sm:px-6 lg:px-8 pt-8">
      {activeTab === 'intake' && <IntakeForm />}
      {activeTab === 'report' && <AssessmentReport />}
      {activeTab === 'history' && <HistoryTracker />}
    </main>
  );
};

export function App() {
  return (
    <TrichologyProvider>
      <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col selection:bg-emerald-500 selection:text-slate-950">
        <Header />
        <div className="flex-1">
          <MainContent />
        </div>

        {/* Clinical Footer */}
        <footer className="glass-panel border-t border-slate-800/80 py-8 px-4 sm:px-6 lg:px-8 mt-auto">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-center md:text-left">
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 rounded-lg bg-emerald-950 border border-emerald-800 flex items-center justify-center text-emerald-400">
                <Dna className="w-4 h-4" />
              </div>
              <div>
                <p className="text-xs font-bold text-white tracking-wide">
                  TRICHOLOGY<span className="text-emerald-400">AI</span> Intelligence Platform
                </p>
                <p className="text-[10px] text-slate-400">Powered by Computer Vision & Explainable AI (XAI)</p>
              </div>
            </div>

            <div className="text-[11px] text-slate-400 max-w-md">
              <p>
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 inline mr-1" />
                Medical Disclaimer: Diagnostic predictions generated by Trichology AI are intended strictly for educational and wellness lifestyle optimization purposes. Always consult a certified dermatologist for medical diagnosis.
              </p>
            </div>

            <div className="text-xs text-slate-400 font-mono">
              <span>© {new Date().getFullYear()} Trichology AI • Privacy First</span>
            </div>
          </div>
        </footer>
      </div>
    </TrichologyProvider>
  );
}

export default App;
